<Project Sdk="Microsoft.NET.Sdk">

	<PropertyGroup>
		<TargetFramework>net6.0</TargetFramework>
		<OutputType>Library</OutputType>
		<RootNamespace>BepInEx.SplashScreen</RootNamespace>
		<AssemblyName>BepInEx.SplashScreen.Patcher.BepInEx5</AssemblyName>
		<Deterministic>true</Deterministic>

		<AmongUs>C:\Program Files (x86)\Steam\steamapps\common\AMONGUS_TOHF_TEST</AmongUs>
		<BepInExPath>$(AmongUs)\BepInEx</BepInExPath>
	</PropertyGroup>

	<PropertyGroup Condition="'$(Configuration)|$(Platform)'=='Debug|AnyCPU'">
		<DebugType>embedded</DebugType>
		<Optimize>false</Optimize>
		<OutputPath>..\bin\BepInEx\patchers\BepInEx.SplashScreen\</OutputPath>
		<DefineConstants>TRACE;DEBUG;Bep5</DefineConstants>
	</PropertyGroup>

	<PropertyGroup Condition="'$(Configuration)|$(Platform)'=='Release|AnyCPU'">
		<DebugType>embedded</DebugType>
		<Optimize>true</Optimize>
		<OutputPath>..\bin\BepInEx\patchers\BepInEx.SplashScreen\</OutputPath>
		<DefineConstants>TRACE;Bep5</DefineConstants>
	</PropertyGroup>

	<ItemGroup>
		<Reference Include="netstandard">
			<HintPath>$(AmongUs)\dotnet\netstandard.dll</HintPath>
		</Reference>
		<Reference Include="System.Runtime">
			<HintPath>$(AmongUs)\dotnet\System.Runtime.dll</HintPath>
		</Reference>
		<Reference Include="BepInEx.Core">
			<HintPath>$(BepInExPath)\core\BepInEx.dll</HintPath>
		</Reference>

		<Reference Include="$(BepInExPath)\core\*.dll" />
		<Reference Include="$(BepInExPath)\interop\*.dll" />
	</ItemGroup>

	<Import Project="..\BepInEx.SplashScreen.Patcher.Common\BepInEx.SplashScreen.Patcher.Common.projitems" Label="Shared" />

</Project>